import {test,expect} from '@playwright/test'
const protocols=['chat-completions','responses','anthropic-messages','gemini-generate-content']
const truncated=protocol=>protocol==='chat-completions'?{choices:[{finish_reason:'length',message:{role:'assistant',content:null}}],usage:{prompt_tokens:20,completion_tokens:32768,total_tokens:32788,completion_tokens_details:{reasoning_tokens:32768}}}
 :protocol==='responses'?{status:'incomplete',incomplete_details:{reason:'max_output_tokens'},output:[]}
 :protocol==='anthropic-messages'?{role:'assistant',stop_reason:'max_tokens',content:[]}
 :{candidates:[{finishReason:'MAX_TOKENS',content:{role:'model',parts:[]}}]}
async function open(page){await page.goto('/');await expect(page.locator('.workbench')).toHaveAttribute('data-demo-state','ready');if((await page.locator('#language').textContent()).trim()==='EN')await page.locator('#language').click();await page.locator('#new-drawing').click();await page.locator('#dialog-fields [name=name]').fill('Output budget test');await page.locator('#dialog-submit').click();await expect(page.locator('#entity-count')).toHaveText('0 entities');if(!(await page.locator('#agent-tab').isVisible()))await page.locator('#toggle-inspector').click();await page.locator('#agent-tab').click()}
async function configure(page,protocol){await page.locator('.chat-connection').click();await page.locator('#chat-endpoint').fill('/api/model');await page.locator('#chat-model').fill('output-budget-protocol-fixture');await page.locator('#chat-protocol').selectOption(protocol);await page.locator('#chat-max-output-tokens').selectOption('32768');await page.getByRole('button',{name:'Use this connection',exact:true}).click()}
test('connection output limit reaches all four protocols and truncated output reports budget without automatic retry',async({page})=>{
 await open(page);const requests=[],revision=await page.locator('#revision').textContent();let protocol=protocols[0]
 await expect(page.locator('#chat-max-output-tokens')).toHaveValue('4096')
 await page.route('**/api/model',route=>{requests.push(route.request().postDataJSON());return route.fulfill({json:truncated(protocol)})})
 for(let index=0;index<protocols.length;index++){
  protocol=protocols[index];await configure(page,protocol);await page.locator('#chat-input').fill('Read this drawing.');await page.locator('#chat-send').click();await expect(page.locator('#chat-input')).toBeEnabled();await expect(page.locator('#chat-messages .chat-message-body').last()).toContainText('exhausted its output-token budget');await expect(page.locator('#chat-messages .chat-message-body').last()).toContainText('including reasoning');await expect(page.locator('#chat-messages .chat-message-body').last()).toContainText('No automatic retry')
  expect(requests).toHaveLength(index+1);const body=requests[index];expect(protocol==='responses'?body.max_output_tokens:protocol==='gemini-generate-content'?body.generationConfig.maxOutputTokens:body.max_tokens).toBe(32768)
 }
 await page.waitForTimeout(250);expect(requests).toHaveLength(4);await expect(page.locator('#entity-count')).toHaveText('0 entities');await expect(page.locator('#revision')).toHaveText(revision);await expect(page.getByRole('button',{name:'Apply changes',exact:true})).toHaveCount(0)
 await page.locator('#language').click();await page.locator('.chat-connection').click();await expect(page.locator('.chat-settings')).toContainText('最大输出 token');await expect(page.locator('.chat-settings')).toContainText('包含推理 token');await page.getByRole('button',{name:'使用此连接',exact:true}).click();await page.locator('#chat-input').fill('读取当前图纸');await page.locator('#chat-send').click();await expect(page.locator('#chat-messages .chat-message-body').last()).toContainText('模型耗尽了输出 token 额度');await expect(page.locator('#chat-input')).toBeEnabled();expect(requests).toHaveLength(5)
})
test('server output-token policy rejection tells users to lower the limit instead of retrying a connection',async({page})=>{
 await open(page);let calls=0;await page.route('**/api/model',route=>{calls++;return route.fulfill({status:400,json:{error:{code:'MODEL_TOKEN_LIMIT'}}})});await configure(page,'chat-completions');await page.locator('#chat-input').fill('Draw a road.');await page.locator('#chat-send').click();await expect(page.locator('#chat-messages .chat-message-body').last()).toContainText('server rejected the requested output-token limit');await expect(page.locator('#chat-input')).toBeEnabled();expect(calls).toBe(1);await expect(page.locator('#entity-count')).toHaveText('0 entities')
})
