import { test, expect } from '@playwright/test'
import { readFile, mkdir } from 'node:fs/promises'
import { createKJDrawSDK, KJProjectSession } from '../../packages/kjdraw-sdk/src/index.js'

async function emptyDrawing(page) {
  const sdk = createKJDrawSDK(), drawing = sdk.createDocument({ documentId: 'empty-drafting', title: 'Mounting plate', units: 'millimeter' })
  const content = await sdk.writeDocument(drawing, { format: 'KJD' })
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/')
  await expect(page.locator('.workbench')).toHaveAttribute('data-demo-state', 'ready')
  await page.locator('#file-input').setInputFiles({ name: 'mounting-plate.kjd', mimeType: 'application/json', buffer: Buffer.from(content) })
  await expect(page.locator('#file-state')).toContainText('Opened locally')
  await expect(page.locator('#entity-count')).toHaveText('0 entities')
  if (await page.locator('#snap').getAttribute('aria-pressed') === 'true') await page.locator('#snap').click()
}
async function command(page, value) {
  await expect(page.locator('.workbench')).toHaveAttribute('aria-busy', 'false')
  await page.locator('#command-input').fill(value)
  await page.locator('#command-input').press('Enter')
  await expect(page.locator('.workbench')).toHaveAttribute('aria-busy', 'false')
  expect(await page.locator('.workbench').getAttribute('data-last-error')).toBeNull()
}
async function draw(page, tool, coordinates, finish = false) {
  await command(page, tool)
  for (const coordinate of coordinates) await command(page, coordinate)
  if (finish) await command(page, finish === 'close' ? 'C' : '')
  await page.locator('#command-input').press('Escape')
}
async function save(page) {
  await page.locator('.ribbon-tabs [data-i18n="home"]').click()
  const pending = page.waitForEvent('download')
  await page.locator('#save').click()
  const download = await pending, bytes = await readFile(await download.path())
  const session = await KJProjectSession.open(bytes, { sdk: createKJDrawSDK() })
  const snapshot = session.activeDocument.snapshot()
  session.destroy()
  return { bytes, snapshot, entities: Object.values(snapshot.objects).filter(object => object.kind === 'entity') }
}
async function platePoint(page, x, y) {
  const box = await page.locator('#canvas').boundingBox(), scale = Math.min((box.width - 164) / 180, (box.height - 164) / 120)
  return { x: box.x + box.width / 2 + (x - 90) * scale, y: box.y + box.height / 2 - (y - 60) * scale }
}

test('draw a mounting plate from empty, polar-array holes, annotate, undo and reopen', async ({ page }, testInfo) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await emptyDrawing(page)
  await draw(page, 'RECTANGLE', ['0,0', '180,120'])
  await draw(page, 'CIRCLE', ['90,60', '22'])
  await draw(page, 'CIRCLE', ['130,60', '5'])
  await command(page, 'FIT')
  const hole = await platePoint(page, 135, 60)
  await page.mouse.click(hole.x, hole.y)
  await expect(page.locator('#selection-count')).toHaveText('1 selected')
  await page.locator('.ribbon-tabs [data-i18n="modify"]').click()
  await page.locator('#modification-tool').selectOption('array-polar')
  await expect(page.locator('#app-dialog')).toBeVisible()
  await page.locator('#dialog-fields input[name="count"]').fill('6')
  await page.locator('#dialog-fields input[name="angleDegrees"]').fill('360')
  await page.locator('#dialog-fields input[name="rotateItems"]').uncheck()
  await page.locator('#dialog-submit').click()
  await command(page, '90,60')
  await expect(page.locator('#entity-count')).toHaveText('8 entities')
  const array = await save(page)
  // Rotated Float64 matrices can change the stored radius by a final-bit rounding error.
  const holes = array.entities.filter(entity => entity.type === 'CIRCLE' && Math.abs(entity.payload.radius - 5) < 1e-9)
  expect(holes).toHaveLength(6)
  for (const entity of holes) {
    expect(entity.payload.radius).toBeCloseTo(5, 12)
    expect(Math.hypot(entity.payload.center[0] - 90, entity.payload.center[1] - 60)).toBeCloseTo(40, 8)
  }
  await command(page, 'UNDO'); await expect(page.locator('#entity-count')).toHaveText('3 entities')
  await command(page, 'REDO'); await expect(page.locator('#entity-count')).toHaveText('8 entities')
  await draw(page, 'DIMALIGNED', ['0,0', '180,0', '90,-15'])
  await draw(page, 'DIMRADIUS', ['90,60', '112,60'])
  await command(page, 'FIT')
  const saved = await save(page)
  expect(saved.entities.filter(entity => entity.type === 'DIMENSION')).toHaveLength(2)
  if (testInfo.project.name === 'chromium') {
    await mkdir('.cache/cad-workflow', { recursive: true })
    await page.screenshot({ path: '.cache/cad-workflow/mounting-plate.png' })
  }
  await page.locator('#file-input').setInputFiles({ name: 'mounting-plate.kjp', mimeType: 'application/zip', buffer: saved.bytes })
  await expect(page.locator('#file-state')).toContainText('Opened locally')
  expect((await save(page)).snapshot.objects).toEqual(saved.snapshot.objects)
  const pending = page.waitForEvent('download'); await page.locator('#export').click()
  const dxf = await readFile(await (await pending).path(), 'utf8')
  const imported = await createKJDrawSDK().readDocument(dxf, { format: 'DXF' })
  expect(imported.listEntities().filter(entity => entity.type === 'DIMENSION')).toHaveLength(2)
  expect(errors).toEqual([])
})

test('construct native curves, closed polylines, hatch and dimensions with exact coordinates', async ({ page }) => {
  await emptyDrawing(page)
  await draw(page, 'PLINE', ['0,0', '@40,0', '@10,20', '@-20,20', '@-30,-10'], 'close')
  await draw(page, 'CIRCLE2P', ['60,0', '80,0'])
  await draw(page, 'CIRCLE3P', ['90,0', '100,10', '110,0'])
  await draw(page, 'ARC3P', ['0,50', '10,60', '20,50'])
  await draw(page, 'ELLIPSE', ['50,60', '70,60', '50,68'])
  await draw(page, 'SPLINE', ['0,80', '20,110', '40,60', '60,90', '80,80'], true)
  await draw(page, 'HATCH', ['85,50', '110,50', '110,70', '85,70'], true)
  await draw(page, 'POLYGON', ['100,100', '110,100'])
  await draw(page, 'DIMLINEAR', ['0,0', '40,0', '20,-10'])
  await draw(page, 'DIMDIAMETER', ['60,0', '80,0'])
  await draw(page, 'LINE', ['120,0', '@10<90'])
  await draw(page, 'RAY', ['120,30', '130,40'])
  await draw(page, 'XLINE', ['120,50', '130,60'])
  await draw(page, 'POINT', ['120,70'])
  const result = await save(page), entities = result.entities
  expect(entities).toHaveLength(14)
  const polyline = entities.find(entity => entity.type === 'LWPOLYLINE' && entity.payload.vertices.length === 5)
  expect(polyline.payload.closed).toBe(true)
  expect(polyline.payload.vertices.at(-1).point.slice(0, 2)).toEqual([0, 30])
  const ellipse = entities.find(entity => entity.type === 'ELLIPSE')
  expect(ellipse.payload.ratio).toBeCloseTo(.4, 10)
  const spline = entities.find(entity => entity.type === 'SPLINE')
  expect(spline.payload.controlPoints).toHaveLength(5); expect(spline.payload.knots).toHaveLength(9)
  const hatch = entities.find(entity => entity.type === 'HATCH')
  expect(hatch.payload.solid).toBe(false); expect(hatch.payload.patternName).toBe('ANSI31')
  expect(entities.find(entity => entity.type === 'ARC').payload.radius).toBeCloseTo(10, 8)
  const line = entities.find(entity => entity.type === 'LINE')
  expect(line.payload.end[0]).toBeCloseTo(120, 8); expect(line.payload.end[1]).toBeCloseTo(10, 8)
  // A partially drawn shape is never saved; undo-point and Escape are draft-only.
  await command(page, 'PLINE'); await command(page, '0,0'); await command(page, '5,5'); await command(page, 'U')
  await page.locator('#command-input').press('Escape')
  expect((await save(page)).snapshot.objects).toEqual(result.snapshot.objects)
})

test('language changes retain picked points and construction options cannot silently erase a draft', async ({ page }) => {
  await emptyDrawing(page)
  await command(page, 'CIRCLE'); await command(page, '10,20')
  await page.locator('#language').click()
  await expect(page.locator('#hint')).toContainText('1 点')
  await page.locator('#circle-mode').selectOption('3-point')
  await expect(page.locator('#circle-mode')).toHaveValue('center-radius')
  await expect(page.locator('#status')).toContainText('请先完成')
  await command(page, '8')
  await page.locator('#command-input').press('Escape')
  const circle = (await save(page)).entities.find(entity => entity.type === 'CIRCLE')
  expect(circle.payload.center.slice(0,2)).toEqual([10,20]); expect(circle.payload.radius).toBe(8)
  // Invalid options in another tool do not poison ordinary line construction.
  await command(page, 'POLYGON')
  await page.locator('#polygon-sides').fill('')
  await draw(page, 'LINE', ['0,0','30,0'])
  await expect(page.locator('#entity-count')).toHaveText('2 个对象')
  await page.locator('#language').click()
  await expect(page.locator('#entity-count')).toHaveText('2 entities')
})

test('new drawing exposes units and command Enter opens a parameter dialog without dismissing it', async ({ page }) => {
  await emptyDrawing(page)
  await page.locator('#new-drawing').click()
  await page.locator('#dialog-fields input[name="name"]').fill('Workshop detail')
  await page.locator('#dialog-fields select[name="units"]').selectOption('inch')
  await page.locator('#dialog-fields input[name="name"]').press('Enter')
  await expect(page.locator('#app-dialog')).not.toBeVisible()
  await expect(page.locator('#sample-select option:checked')).toHaveText('Workshop detail')
  await draw(page, 'LINE', ['0,0','10,0'])
  await command(page, 'FIT')
  const box=await page.locator('#canvas').boundingBox()
  await page.mouse.click(box.x+box.width/2, box.y+box.height/2)
  await expect(page.locator('#selection-count')).toHaveText('1 selected')
  await page.locator('#command-input').fill('ROTATE'); await page.locator('#command-input').press('Enter')
  await expect(page.locator('#app-dialog')).toBeVisible()
  await page.locator('#dialog-fields input[name="angleDegrees"]').fill('90')
  await page.locator('#dialog-fields input[name="angleDegrees"]').press('Enter')
  await command(page, '0,0')
  const saved=await save(page), line=saved.entities.find(entity=>entity.type==='LINE')
  expect(saved.snapshot.header.units).toBe('inch')
  expect(line.payload.end[0]).toBeCloseTo(0,10); expect(line.payload.end[1]).toBeCloseTo(10,10)
})
