import { expect, test } from '@playwright/test'

test.use({ bypassCSP: true })

test('Workbench exposes an atomic full layer editor and batch entity styles',async({page})=>{
  await page.goto('/')
  await page.evaluate(async()=>{
    document.body.replaceChildren();const host=document.createElement('div');host.style.cssText='width:1200px;height:760px';document.body.append(host)
    const [{createKJDrawSDK},{mountKJDrawWorkbench}]=await Promise.all([import('/packages/kjdraw-sdk/src/sdk.js'),import('/packages/kjdraw-sdk/src/workbench.js')])
    const sdk=createKJDrawSDK(),drawing=sdk.createDocument({documentId:'layer-workbench-ui'}),dashed=await sdk.executeCommand('LINETYPE',{name:'KJ-DASH',pattern:[4,-2]},{document:drawing})
    const a=await sdk.executeCommand('CREATE',{type:'LINE',payload:{start:[0,0],end:[10,0]}},{document:drawing}),b=await sdk.executeCommand('CREATE',{type:'CIRCLE',payload:{center:[5,5],radius:2}},{document:drawing})
    const workbench=mountKJDrawWorkbench(host,{sdk,document:drawing,locale:'en',theme:'light'});await workbench.ready;window.layerTest={sdk,drawing,workbench,dashed,ids:[a.id,b.id]}
  })
  const root=page.locator('.kjwb')
  await root.locator('[data-action="new-layer"]').click()
  const dialog=root.locator('[data-layer-dialog="new"]');await expect(dialog).toBeVisible()
  await dialog.locator('[data-layer-name]').fill('FAB')
  await dialog.locator('[data-layer-color]').fill('3')
  await dialog.locator('[data-layer-linetype]').selectOption({label:'KJ-DASH'})
  await dialog.locator('[data-layer-lineweight]').selectOption('35')
  await dialog.locator('[data-layer-property="current"]').check()
  const before=await page.evaluate(()=>window.layerTest.drawing.revision)
  await dialog.getByRole('button',{name:'Apply'}).click();await expect(dialog).toHaveCount(0)
  const identity=await page.evaluate(()=>{const d=window.layerTest.drawing,l=d.getTable('layers').records.find(x=>x.name==='FAB');return{id:l.id,handle:l.handle,current:d.getTable('layers').currentId,revision:d.revision}})
  expect(identity.current).toBe(identity.id);expect(identity.revision).toBe(before+1)
  await expect(root.locator(`[data-layer-current="${identity.id}"]`)).toHaveAttribute('aria-pressed','true')
  await page.evaluate(()=>window.layerTest.sdk.getSelectionManager(window.layerTest.drawing.id).active.replace(window.layerTest.ids))
  const inspector=root.locator('[data-inspector]');await expect(inspector).toContainText('2 selected')
  await inspector.locator('[data-property="layer"]').selectOption(identity.id)
  await inspector.locator('[data-property="color"]').selectOption('2')
  const dashedId=await page.evaluate(()=>window.layerTest.dashed.id)
  await inspector.locator('[data-property="linetype"]').selectOption(dashedId)
  await inspector.locator('[data-property="lineweight"]').selectOption('50')
  await inspector.getByRole('button',{name:'Apply'}).click()
  await expect.poll(()=>page.evaluate(()=>window.layerTest.ids.map(id=>{const e=window.layerTest.drawing.getObject(id);return[e.payload.layerId,e.payload.color,e.payload.linetypeId,e.payload.lineweight]}))).toEqual([[identity.id,2,dashedId,50],[identity.id,2,dashedId,50]])
  await root.locator('[data-action="undo"]').click();await expect.poll(()=>page.evaluate(()=>window.layerTest.ids.map(id=>window.layerTest.drawing.getObject(id).payload.color??256))).toEqual([256,256])
  await root.locator('[data-action="redo"]').click();await expect.poll(()=>page.evaluate(()=>window.layerTest.ids.map(id=>window.layerTest.drawing.getObject(id).payload.color))).toEqual([2,2])
  await root.locator(`[data-layer-edit="${identity.id}"]`).click();const edit=root.locator(`[data-layer-dialog="${identity.id}"]`)
  await edit.locator('[data-layer-name]').fill('FAB-LOCKED');await edit.locator('[data-layer-color]').fill('5');await edit.locator('[data-layer-lineweight]').selectOption('70');await edit.locator('[data-layer-property="locked"]').check();await edit.locator('[data-layer-property="frozen"]').check();await edit.locator('[data-layer-property="visible"]').uncheck();await edit.getByRole('button',{name:'Apply'}).click()
  await expect(edit).toHaveCount(0)
  expect(await page.evaluate(id=>{const l=window.layerTest.drawing.getObject(id);return[l.id,l.handle,l.name,l.payload.color,l.payload.lineweight,l.payload.visible,l.payload.locked,l.payload.frozen]},identity.id)).toEqual([identity.id,identity.handle,'FAB-LOCKED',5,70,false,true,true])
})

test('Playground creates, activates and edits full layer properties from its layer panel',async({page})=>{
  await page.goto('/')
  await expect(page.locator('.workbench')).toHaveAttribute('data-demo-state','ready',{timeout:70000})
  if(!(await page.locator('.workbench').getAttribute('class')).includes('layers-open'))await page.locator('#toggle-layers').click()
  await page.locator('#new-layer').click();const fields=page.locator('#dialog-fields')
  await fields.locator('input[name="name"]').fill('UI-LAYER')
  await fields.locator('input[name="color"]').fill('4')
  await fields.locator('select[name="lineweight"]').selectOption('70')
  await fields.locator('input[name="current"]').check()
  await page.locator('#dialog-submit').click()
  const row=page.locator('.layer[data-layer-name="UI-LAYER"]');await expect(row).toBeVisible();await expect(row.locator('.layer-current')).toHaveAttribute('aria-pressed','true')
  await row.getByRole('button',{name:/Layer settings|图层设置/}).click()
  await fields.locator('input[name="name"]').fill('UI-LAYER-RENAMED')
  await fields.locator('input[name="color"]').fill('6')
  await fields.locator('select[name="lineweight"]').selectOption('100')
  await page.locator('#dialog-submit').click()
  await expect(page.locator('.layer[data-layer-name="UI-LAYER-RENAMED"]')).toBeVisible()
})
