import { readFile } from 'node:fs/promises'
import { expect, test } from '@playwright/test'

if (process.env.KJDRAW_TEST_BASE_URL) test.use({ baseURL: process.env.KJDRAW_TEST_BASE_URL })

test('playground object-snap settings are user-editable, undoable and preserved by KJP reopen', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.goto('/')
  await expect(page.locator('.workbench')).toHaveAttribute('data-demo-state', 'ready')
  const dialog=page.locator('#hotkey-settings-dialog'),revision=page.locator('#revision')
  const openSnaps=async()=>{await page.locator('#settings').click();await expect(page.locator('#settings-tab-snaps')).toHaveAttribute('aria-selected','true')}
  const checked=()=>dialog.locator('[data-snap-mode]:checked').evaluateAll(inputs=>inputs.map(input=>input.value))

  await openSnaps()
  expect(await checked()).toEqual(['endpoint','midpoint','center','quadrant','nearest','intersection','perpendicular','tangent'])
  await expect(page.locator('#snap-aperture')).toHaveValue('10')
  for(const input of await dialog.locator('[data-snap-mode]').all())await input.uncheck()
  await dialog.locator('[data-snap-mode="endpoint"]').check()
  await dialog.locator('[data-snap-mode="quadrant"]').check()
  await page.locator('#snap-aperture').fill('14')
  const before=await revision.textContent()
  await page.locator('#hotkey-apply').click()
  await expect(dialog).toBeHidden()
  await expect(revision).not.toHaveText(before)

  await openSnaps()
  expect(await checked()).toEqual(['endpoint','quadrant'])
  await expect(page.locator('#snap-aperture')).toHaveValue('14')
  await page.locator('#snap-aperture').fill('0')
  await page.locator('#hotkey-apply').click()
  await expect(dialog).toBeVisible()
  await expect(page.locator('#snap-aperture')).toHaveAttribute('aria-invalid','true')
  await page.locator('#snap-aperture').fill('30')
  const appliedRevision=await revision.textContent()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(revision).toHaveText(appliedRevision)
  await openSnaps()
  await expect(page.locator('#snap-aperture')).toHaveValue('14')
  await page.locator('#hotkey-cancel').click()

  await page.locator('#undo').click()
  await openSnaps()
  await expect(page.locator('#snap-aperture')).toHaveValue('10')
  expect(await checked()).toEqual(['endpoint','midpoint','center','quadrant','nearest','intersection','perpendicular','tangent'])
  await page.locator('#hotkey-cancel').click()
  await page.locator('#redo').click()

  const pending=page.waitForEvent('download')
  await page.locator('#save').click()
  const bytes=await readFile(await (await pending).path())
  await page.locator('#file-input').setInputFiles({name:'snap-settings.kjp',mimeType:'application/zip',buffer:bytes})
  await expect(page.locator('#file-state')).toContainText('Opened locally')
  await openSnaps()
  expect(await checked()).toEqual(['endpoint','quadrant'])
  await expect(page.locator('#snap-aperture')).toHaveValue('14')
  await page.locator('#hotkey-cancel').click()
  await page.locator('#language').click()
  await openSnaps()
  await expect(page.locator('#hotkey-settings-title')).toHaveText('设置')
  await expect(page.locator('#settings-tab-snaps')).toHaveText('对象捕捉')
})
