import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

test('Precision theme keeps CAD controls readable and panels usable', async ({ page }, testInfo) => {
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.setViewportSize({width:1440,height:900})
  await page.goto('/')
  await expect(page.locator('.workbench')).toHaveAttribute('data-demo-state','ready')
  await expect(page.locator('.site-header #sample-select')).toHaveCount(1)
  await expect(page.locator('#open .kj-icon')).toHaveCount(1)
  await expect(page.locator('#open span')).toHaveText('Open')
  expect(await page.locator('#open').evaluate(el=>getComputedStyle(el).fontSize)).toBe('12px')
  expect(await page.locator('body').evaluate(el=>getComputedStyle(el).getPropertyValue('--kj-action').trim())).toBe('#2863df')
  await page.locator('#toggle-layers').click()
  await expect(page.locator('.left-panel')).toBeVisible()
  await page.locator('#layer-search').fill('no-such-layer')
  await expect(page.locator('#layers .layer:visible')).toHaveCount(0)
  await expect(page.locator('#layer-search-empty')).toBeVisible()
  await page.locator('#layer-search').fill('')
  await expect(page.locator('#layers .layer:visible')).toHaveCount(11)
  const layer=page.locator('#layers .layer').first()
  const toggle=layer.locator('input[type=checkbox]')
  await toggle.uncheck();await expect(toggle).not.toBeChecked()
  await page.locator('#undo').click();await expect(toggle).toBeChecked()
  await layer.locator('button').click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.locator('input[name=color]').fill('3')
  await page.locator('#dialog-submit').click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(layer.locator('i')).toHaveCSS('background-color','rgb(0, 255, 0)')
  await page.locator('#undo').click()
  const panel=page.locator('.left-panel'),before=(await panel.boundingBox()).width
  await panel.locator('[role=separator]').focus()
  await page.keyboard.press('ArrowRight')
  expect((await panel.boundingBox()).width).toBeGreaterThan(before)
  await page.locator('#language').click()
  await expect(page.locator('#open span')).toHaveText('打开')
  await expect(page.locator('#open .kj-icon')).toHaveCount(1)
  for(const [width,height] of [[1366,768],[1440,900],[1920,1080],[390,844]]){
    await page.setViewportSize({width,height})
    await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    const bounds=await page.locator('#canvas').boundingBox()
    expect(bounds.width).toBeGreaterThan(width===390?300:700)
    expect(bounds.height).toBeGreaterThan(440)
    if(testInfo.project.name==='chromium'){
      await mkdir('.cache/precision',{recursive:true})
      await page.screenshot({path:`.cache/precision/workbench-${width}.png`})
    }
  }
  expect(errors).toEqual([])
})

test('ribbon sections and example review do what their labels promise',async({page})=>{
  await page.goto('/')
  await expect(page.locator('.workbench')).toHaveAttribute('data-demo-state','ready')
  await page.locator('.ribbon-tabs button[data-i18n=modify]').click()
  await expect(page.locator('#move-selection')).toBeVisible()
  await expect(page.locator('[data-tool=line]')).toBeHidden()
  await page.locator('.ribbon-tabs button[data-i18n=home]').click()
  await expect(page.locator('[data-tool=line]')).toBeVisible()
  await page.locator('#agent-tab').click()
  await expect(page.locator('#plan')).toBeDisabled()
  await page.locator('#open-agent-sample').click()
  await expect(page.locator('#sample-select')).toHaveValue('sample-resilient-campus')
  await expect(page.locator('#agent-intent')).toHaveAttribute('readonly','')
  await expect(page.locator('#agent-help')).toContainText('not a connected AI model')
  await page.locator('#plan').click()
  await expect(page.locator('#plan-state')).toHaveAttribute('data-state','planned')
  await expect(page.locator('#confirm')).toBeEnabled()
})
