import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import test from 'node:test'

const root = new URL('../../../', import.meta.url)
const read = path => readFile(new URL(path, root), 'utf8')
const channel = JSON.parse(await read('scripts/install-ai-channel.json'))

test('one-line AI bootstraps pin one public candidate and connect all clients without npx or force', async () => {
  const [powerShell, shell] = await Promise.all([read('scripts/install-ai.ps1'), read('scripts/install-ai.sh')])
  assert.equal(channel.schema, 'com.kanjie.kjdraw.install-channel@1')
  assert.match(channel.sourceSha, /^[0-9a-f]{40}$/u)
  for (const source of [powerShell, shell]) {
    assert.match(source, /install-ai-channel\.json/)
    assert.match(source, /com\.kanjie\.kjdraw\.install-channel@1/)
    assert.match(source, /\^\[0-9a-f\]\{40\}\$/)
    assert.match(source, /source-9ae1988/)
    assert.match(source, /kjdraw-connect\.mjs/)
    assert.match(source, /kjdraw-mcp\.mjs/)
    assert.match(source, /--check-tool-schemas/)
    assert.match(source, /moonshot-walle-compatible-v1/)
    assert.match(source, /codeload\.github\.com\/KanJieTeam\/kjdraw/)
    for (const option of ['--all', '--apply', '--scope', '--workspace']) assert.match(source, new RegExp(option))
    assert.match(source, /--input|--blank/)
    assert.match(source, /\.kjdraw\/host\.kjd/)
    assert.match(source, /--candidate-dir/)
    assert.match(source, /\.kjdraw\/results/)
    assert.match(source, /--previous-mcp-script/)
    assert.match(source, /--replace-existing/); assert.match(source, /--replace-existing-skill/)
    assert.match(source, /--mcp-script/)
    assert.match(source, /current\.json/)
    assert.match(source, /com\.kanjie\.kjdraw\.install-current@1/)
    assert.match(source, /kjdraw-installed-mcp\.mjs/)
    assert.match(source, /in-place upgrades/)
    for (const previous of ['source-000d7f7', 'source-ddb0b53', 'source-bb17394', 'source-734a7f4', 'source-4c7124e', 'source-0c2d86e', 'source-57e0697', 'source-1854240', 'source-5f655c2', 'source-69bec87', 'source-7b25cf4', 'source-b022932', 'source-6da40b2', 'source-85d750e', 'source-c526aa7', 'source-a3c1bca', 'source-71df822', 'source-616133e', 'source-2a793ad', 'source-be1e4b5', 'source-6977028', 'source-1a6ff8c', 'source-87cf874', 'source-e74812f', 'source-03d170d', 'source-73c7975', 'source-381ce68', 'source-8374659', 'source-b99e13b']) assert.match(source, new RegExp(previous))
    assert.doesNotMatch(source, /KJDRAW_PROJECT|Get-Location|\$PWD/)
    assert.doesNotMatch(source, /\bnpx\b|git clone|push|--force|reset --hard/)
  }
  assert.match(powerShell, /KJDrawSourceSha\.Substring\(0, 7\)/)
  assert.match(shell, /KJDRAW_SOURCE_SHORT/)
  assert.match(shell, /KJDRAW_PREVIOUS_9AE/)
  assert.match(powerShell, /IsPathRooted/)
  assert.doesNotMatch(powerShell, /IsPathFullyQualified/)
  assert.match(powerShell, /\$KJDrawArgs \+= @\('--mcp-script', \$KJDrawStableMcp\)/)
  assert.match(powerShell, /\$KJDrawArgs \+= '--replace-existing'/)
  assert.match(powerShell, /\$KJDrawArgs \+= '--replace-existing-skill'/)
  assert.doesNotMatch(powerShell, /^\s*\+=/mu)
  assert.match(powerShell, /Install-KJDrawAtomicFile \$KJDrawCurrentStage \$KJDrawCurrent/)
  assert.match(powerShell, /UTF8Encoding\(\$false\)/)
  assert.match(powerShell, /earlier KJDraw MCP process is still attached/u)
  assert.match(powerShell, /Existing candidate HTML files are immutable/u)
  assert.match(powerShell, /WindowsIdentity/u)
  assert.match(powerShell, /active Windows desktop belongs to/u)
  assert.match(powerShell, /same account that runs WorkBuddy/u)
  assert.match(powerShell, /128 MiB free/u)
  assert.match(powerShell, /Cleanup must never replace the real download/u)
  assert.match(powerShell, /ErrorAction SilentlyContinue/u)
  assert.doesNotMatch(powerShell, /Stop-Process|taskkill/u)
  assert.match(powerShell, /^[\x00-\x7f]*$/u)
  assert.match(shell, /set -- "\$@" --mcp-script "\$KJDRAW_STABLE_MCP" --replace-existing/)
  assert.match(shell, /mv -f "\$KJDRAW_CURRENT_STAGE" "\$KJDRAW_CURRENT"/)
  assert.match(shell, /trap .*KJDRAW_CURRENT_STAGE/)
})

test('English default and Chinese homepage lead with the same runnable one-command AI install', async () => {
  const [english, chinese] = await Promise.all([read('README.md'), read('README.zh-CN.md')])
  for (const source of [chinese, english]) {
    assert.match(source, /irm https:\/\/raw\.githubusercontent\.com\/KanJieTeam\/kjdraw\/main\/scripts\/install-ai\.ps1 \| iex/)
    assert.match(source, /curl -fsSL https:\/\/raw\.githubusercontent\.com\/KanJieTeam\/kjdraw\/main\/scripts\/install-ai\.sh \| sh/)
  }
})
