import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { spawnSync } from 'node:child_process'
import test from 'node:test'

const repositoryRoot = new URL('../../../', import.meta.url)
const docsRoot = new URL('docs/latest/', repositoryRoot)

async function json(path) {
  return JSON.parse(await readFile(new URL(path, repositoryRoot), 'utf8'))
}

test('generated documentation portal covers the complete bilingual learning path', async () => {
  const packageJson = await json('packages/kjdraw-sdk/package.json')
  const manifest = await json('docs/latest/site-manifest.json')
  const search = await json('docs/latest/search-index.json')
  const required = [
    'introduction', 'quickstart', 'installation', 'workbench', 'architecture', 'react', 'vue',
    'files', 'commands', 'agent', 'models', 'plugins', 'deployment', 'capabilities',
  ]

  assert.equal(manifest.schema, 'com.kanjie.kjdraw.docs-site@1')
  assert.equal(manifest.package, packageJson.name)
  assert.equal(manifest.version, packageJson.version)
  assert.match(manifest.sourceDigest, /^sha256:[a-f0-9]{64}$/)
  assert.deepEqual(new Set(manifest.pages.map(page => page.slug)), new Set(required))
  assert.deepEqual(manifest.locales, ['en', 'zh'])
  const assetRevision = manifest.sourceDigest.slice('sha256:'.length, 'sha256:'.length + 16)

  const htmlByPage = new Map()
  for (const page of manifest.pages) {
    assert.match(page.source, /^docs\/site\/pages\/[a-z0-9-]+\.md$/)
    const html = await readFile(new URL(page.output, docsRoot), 'utf8')
    htmlByPage.set(page.slug, html)
    assert.match(html, /Generated by scripts\/build-docs-site\.mjs/)
    assert.match(html, new RegExp(`data-page=["']${page.slug}["']`))
    assert.match(html, /id="docs-version"/)
    assert.match(html, /class="lang-en"/)
    assert.match(html, /class="lang-zh"/)
    assert.match(html, /api\//)
    assert.match(html, new RegExp(`style\\.css\\?v=${assetRevision}`))
    assert.match(html, new RegExp(`app\\.js\\?v=${assetRevision}`))
    for (const locale of manifest.locales) {
      assert.ok(page.anchors[locale].length >= 2, `${page.slug}/${locale} must expose deep links`)
      for (const anchor of page.anchors[locale]) assert.match(html, new RegExp(`id=["']${anchor}["']`))
    }
  }

  assert.equal(search.schema, 'com.kanjie.kjdraw.docs-search-index@1')
  assert.equal(search.version, packageJson.version)
  assert.equal(search.sourceDigest, manifest.sourceDigest)
  assert.ok(search.entries.length > required.length * 2)
  for (const locale of manifest.locales) {
    const tools = search.entries.find(entry => entry.href.endsWith(`#${locale}-agent-agent-tools`))
    assert.ok(tools, `Agent tool guide must be indexed in ${locale}`)
    assert.match(tools.text, /cad_propose_circles/)
    assert.match(tools.text, /@kanjieteam\/kjdraw\/agent-tools/)
  }
  for (const entry of search.entries) {
    assert.ok(manifest.locales.includes(entry.locale))
    assert.ok(required.includes(entry.page))
    assert.ok(entry.title && entry.summary && entry.text)
    const fragment = entry.href.split('#')[1]
    assert.ok(fragment, `search entry must be a deep link: ${entry.href}`)
    assert.match(htmlByPage.get(entry.page), new RegExp(`id=["']${fragment}["']`))
  }

  const app = await readFile(new URL('app.js', docsRoot), 'utf8')
  assert.match(app, /search-index\.json/)
  assert.match(app, /api\/search-index\.json/)
  assert.match(app, /kjdraw\.docs\.language/)
  assert.match(app, /fetchSearchEntries/)
  assert.match(app, /cache:'no-store'/)
  assert.match(app, /finishIndex\(\).*renderSearch\(\)/)
  assert.doesNotMatch(app, /Promise\.all\(\[/)
  assert.doesNotMatch(app, /Guides and 784/)
})

test('generated documentation portal has no source or navigation drift', () => {
  const result = spawnSync(process.execPath, ['scripts/build-docs-site.mjs', '--check'], {
    cwd: new URL('.', repositoryRoot),
    encoding: 'utf8',
  })
  assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`)
})
